project:
  type: website
  output-dir: docs

website:
  title: "Demo site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - favorite.qmd
      - penguin.qmd
      - testpdf.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true

editor: visual

